[INFO 15:16:03] pymarl Running command 'my_main'
[INFO 15:16:03] pymarl Started run with ID "88"
[DEBUG 15:16:03] pymarl Starting Heartbeat
[DEBUG 15:16:03] my_main Started
[INFO 15:16:03] my_main Experiment Parameters:
[INFO 15:16:03] my_main 

{   'agent': 'rnn',
    'batch_size': 1024,
    'batch_size_run': 32,
    'buffer_cpu_only': True,
    'buffer_size': 32,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'cur_episodes': 32,
    'env': 'overcooked',
    'env_args': {   'dense_reward': True,
                    'layout_name': 'forced_coordination_hard',
                    'reset_when_success': False},
    'episodes_per_teammate': 64,
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'exp_name': 'stage1_overcooked',
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'ind': 'stage1',
    'inner_loop_episodes': 128,
    'label': 'default_label',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'local_saves_path': 'saves',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic',
    'meta_update_times': 8,
    'n_sub_modules': 3,
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimize_meta': True,
    'points_per_teammate': 64,
    'pop': 'stage1',
    'population_alg': 'vdn',
    'population_size': 4,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'meta',
    'runner_log_interval': 10000,
    'save_BR': False,
    'save_BR_episodes': 2048,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_population': True,
    'save_population_episodes': 4096,
    'save_replay': False,
    'seed': 343760224,
    't_max': 10000000,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'test_percent': 0.2,
    'train_test_split': False,
    'use_cuda': True,
    'use_history': False,
    'use_tensorboard': True,
    'z_dim': 8}

Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-1:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-3:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-5:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-2:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-4:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-8:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-7:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-6:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-9:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-12:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-14:
Process Process-11:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Process Process-10:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-15:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-13:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-17:
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Process Process-21:
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Process Process-18:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-16:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-19:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-22:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-20:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-23:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-25:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-24:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-26:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-27:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-31:
Process Process-29:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-28:
Process Process-32:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
Loaded MediumLevelPlanner from /home/cike/code/src/envs/overcooked/overcooked_ai/overcooked_ai_py/data/planners/forced_coordination_hard_am.pkl
Process Process-30:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 17, in env_worker
    env = env_fn.x()
  File "/home/cike/code/src/envs/overcooked/overcookedenv.py", line 69, in __init__
    proj_dir = file_path[:file_path.index('meta_pymarl')+len('meta_pymarl')]
ValueError: substring not found
